### ISSUE TITLE
Add information to "The Event".

### ISSUE THREAD

**Issue by vigliensoni** [DDMAL/ISMIR2020#10]
This is from the ISMIR 2019 site:

The annual conference of the [International Society for Music Information Retrieval](http://ismir.net/) (ISMIR) is the world’s leading research forum on processing, searching, organizing and accessing music-related data. 

The ISMIR Conference provides a meeting place for the discussion of MIR-related research. Its main goal is to foster the exchange of ideas across disciplines by bringing together researchers, developers, educators, librarians, students, and professional users.

ISMIR is a non-profit organization which, among other things, oversees the organization of the ISMIR Conference.

**Comment by emilyhopkins** [comment]
The second two paragraphs here are on event_card.md but don't show up in the event content
They should be moved to the page that has the "Event placeholder" note for now
