### ISSUE TITLE
Popular vote winners

### ISSUE THREAD

**Issue by vigliensoni** [DDMAL/ISMIR2020#18]
Here is the list of winners, to go on the main site

Music program awards

1st place: [A Room with Chaconne (Bach) by Seth Thorn](https://program.ismir2020.net/music_389.html)
2nd place: [Super Colliders by Takuto Fukuda](https://program.ismir2020.net/music_411.html)
3rd place: [I'll Marry You, Punk Come by Dadabots X Portrait XO](https://program.ismir2020.net/music_416.html)

Best poster presentation sessions 1-3: Ethan Manilow, Gordon Wichern, Jonathan LeRoux  for "Hierarchical Musical Instrument Separation"

Best poster presentation sessions 4-6: Gabriel Oliveira, Mariana Santos, Danilo B Seufitelli, Anisio Lacerda, Mirella M Moro for "Detecting Collaboration Profiles in Success-based Music Genre Networks"

Best video, sessions 1-3: Ethan Manilow, Gordon Wichern, Jonathan LeRoux for "Hierarchical Musical Instrument Separation"

Best video, sessions 4-6: Furkan Yesiler, Joan Serra, Emilia Gomez for "Less Is More: Faster and Better Music Version Identification with Embedding Distillation"

Most active conference attendee: Sertan Şentürk

**Comment by napulen** [comment]
Should be ready now! Sorry that I didn't originally see this issue.
