### ISSUE TITLE
Display Event, City, and Participants information in live site

### ISSUE THREAD

**Issue by evansavage** [DDMAL/ISMIR2020#2]
Note: I know this repository is not the one we are using for development (the "live" one is located at https://github.com/ismir/ISMIR2020), but notifications of this one reach interested parties.

We should really have some basic information for "The Event", "City" (a.k.a "Montreal"), and "The Participants" before the presentation of ISMIR 2020 in Delft. This presentation will happen on November 8th, 2019, and so let's shoot to have something for November 1st so we all can review and approve it.

I guess @emilyhopkins can have some info that we can take and put here.

**Comment by vigliensoni** [comment]
See:
- #5 for Important Dates
- #8 for The City
- #9 for Participants
- #10 for The Event
